### ISSUE TITLE
Texto y fondo del mismo color en dropdowns causa que no se vean las opciones

### ISSUE THREAD

**Issue by marcosmarp** [koaladlt/PeerPrice-Extension#2]
Buenas, v2.0.1 de la extensión, v109.0.5414.75 de chrome con un tema default de chrome en light mode, todos los dropdowns se ven así:
![image](https://user-images.githubusercontent.com/88422056/212721430-bb7de753-088e-4ab2-babd-92ec9e75a315.png)

Para ver la opción tenes que hacer hover o seleccionarla

**Comment by koaladlt** [comment]
Gracias Marcos! Te aviso cuando esté el fix

**Comment by koaladlt** [comment]
@marcosmarp Consulta, estás usando Windows?

**Comment by marcosmarp** [comment]
@koaladlt sep

**Comment by koaladlt** [comment]
@marcosmarp fixed acá: https://github.com/koaladlt/PeerPrice-Extension/pull/3

Ya enviada la nueva versión 2.0.2 al store de Chrome, mañana ya debería estar aprobada.

Dejo abierto el issue hasta que lo pruebes

**Comment by koaladlt** [comment]
@marcosmarp.

Ya publicado. Contame si se solucionó (capaz que tarde un rato en actualizar, o para que se aplique más rápido por [desinstalar e instalar](https://chrome.google.com/webstore/detail/peerprice/dnliacgmindidcbcjalfpeklfpioholi/related?hl=es&authuser=1) la extensión de nuevo)

**Comment by marcosmarp** [comment]
buenas, ahora se ve joya. gracias!
